image: ruby:2.2

stages:
  - deploy

before_script:
  - whoami
#  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#  - cat ~/.ssh/id_rsa
#  - pwd
#  - chmod 0600 ~/.ssh/id_rsa

 # install ssh-agent
#  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  # run ssh-agent
  - eval $(ssh-agent -s)
  # add ssh key stored in SSH_PRIVATE_KEY variable to the agent store
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  # disable host key checking (NOTE: makes you susceptible to man-in-the-middle attacks)
  # WARNING: use only in docker container, if you use it with shell you will overwrite your user's ssh config
  - mkdir -p ~/.ssh
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config




test_site:
  stage: deploy
  tags:
    - formulad
  script:
    - echo "potencialmente destructivo"
    - mkdir temp
    - cd temp
    - git clone --recursive git@gitlab.com:formulad/site-theme.git
    - cd ./site-theme/fd/content
    - git checkout master && git pull
    - cd ../../
    - git add *
    - git commit -m "Pulled down latest content from site-content"
    - git push origin master
